import type { ApiAppointment, TenantDoctor, TenantService } from './types';

export const DEMO_APPOINTMENTS: ApiAppointment[] = [
  {
    id: 'demo-1',
    tenantId: 'demo-tenant',
    patientId: 'p-1',
    doctorId: 'd-1',
    serviceId: 's-1',
    startTime: '2026-09-09T15:00:00.000Z',
    endTime: '2026-09-09T15:45:00.000Z',
    status: 'CONFIRMED',
    paymentStatus: 'DEPOSIT_PAID',
    depositAmountMxn: 200,
    channelOrigin: 'WHATSAPP',
    symptoms: 'Limpieza semestral de rutina',
    notes: 'Confirmada por WhatsApp',
    createdAt: '2026-09-08T10:00:00.000Z',
    patient: { id: 'p-1', fullName: 'Mariana Hernández', phoneE164: '+52 (55) 1234-9988' },
    doctor: { id: 'd-1', name: 'Dra. Sofía Silva', specialty: 'Odontología General y Estética' },
    service: { id: 's-1', name: 'Limpieza Dental con Ultrasonido', priceMxn: 850, durationMinutes: 45 },
  },
  {
    id: 'demo-2',
    tenantId: 'demo-tenant',
    patientId: 'p-2',
    doctorId: 'd-1',
    serviceId: 's-2',
    startTime: '2026-09-09T16:00:00.000Z',
    endTime: '2026-09-09T17:00:00.000Z',
    status: 'CONFIRMED',
    paymentStatus: 'DEPOSIT_PAID',
    depositAmountMxn: 500,
    channelOrigin: 'WHATSAPP',
    symptoms: 'Aclaramiento para boda',
    notes: 'Anticipo acreditado con Mercado Pago',
    createdAt: '2026-09-08T11:00:00.000Z',
    patient: { id: 'p-2', fullName: 'Laura Patricia Vega', phoneE164: '+52 (55) 4433-2211' },
    doctor: { id: 'd-1', name: 'Dra. Sofía Silva', specialty: 'Estética Dental' },
    service: { id: 's-2', name: 'Blanqueamiento Dental LED', priceMxn: 2600, durationMinutes: 60 },
  },
  {
    id: 'demo-3',
    tenantId: 'demo-tenant',
    patientId: 'p-3',
    doctorId: 'd-2',
    serviceId: 's-3',
    startTime: '2026-09-09T17:30:00.000Z',
    endTime: '2026-09-09T19:00:00.000Z',
    status: 'CONFIRMED',
    paymentStatus: 'DEPOSIT_PAID',
    depositAmountMxn: 300,
    channelOrigin: 'PHONE_CALL',
    symptoms: 'Dolor agudo nocturno al masticar',
    notes: 'Atendido por recepcionista IA telefónica',
    createdAt: '2026-09-08T12:00:00.000Z',
    patient: { id: 'p-3', fullName: 'Carlos Gómez', phoneE164: '+52 (55) 8877-6655' },
    doctor: { id: 'd-2', name: 'Dr. Alejandro Morales', specialty: 'Endodoncia y Cirugía' },
    service: { id: 's-3', name: 'Tratamiento de Conductos (Endodoncia)', priceMxn: 3200, durationMinutes: 90 },
  },
  {
    id: 'demo-4',
    tenantId: 'demo-tenant',
    patientId: 'p-4',
    doctorId: 'd-2',
    serviceId: 's-4',
    startTime: '2026-09-09T19:00:00.000Z',
    endTime: '2026-09-09T20:00:00.000Z',
    status: 'URGENT',
    paymentStatus: 'NONE',
    depositAmountMxn: 0,
    channelOrigin: 'PHONE_CALL',
    symptoms: 'Traumatismo dental con sangrado activo',
    notes: '🚨 Triaje Urgencia Prioritaria',
    createdAt: '2026-09-09T08:00:00.000Z',
    patient: { id: 'p-4', fullName: 'Fernando Rivas (Urgencia)', phoneE164: '+52 (55) 7766-5544' },
    doctor: { id: 'd-2', name: 'Dr. Alejandro Morales', specialty: 'Cirugía Maxilofacial' },
    service: { id: 's-4', name: 'Extracción Quirúrgica Urgente', priceMxn: 1950, durationMinutes: 60 },
  },
  {
    id: 'demo-5',
    tenantId: 'demo-tenant',
    patientId: 'p-5',
    doctorId: 'd-1',
    serviceId: 's-1',
    startTime: '2026-09-10T17:00:00.000Z',
    endTime: '2026-09-10T17:45:00.000Z',
    status: 'CONFIRMED',
    paymentStatus: 'DEPOSIT_PENDING',
    depositAmountMxn: 200,
    channelOrigin: 'WHATSAPP',
    symptoms: 'Limpieza dental con ultrasonido y pulido',
    notes: 'Asistencia confirmada vía WhatsApp',
    createdAt: '2026-09-09T09:00:00.000Z',
    patient: { id: 'p-5', fullName: 'JC (Confirmado)', phoneE164: '+52 (81) 2865-1819' },
    doctor: { id: 'd-1', name: 'Dra. Sofía Silva', specialty: 'Odontología General y Estética' },
    service: { id: 's-1', name: 'Limpieza Dental con Ultrasonido y Pulido', priceMxn: 850, durationMinutes: 45 },
  },
  {
    id: 'demo-6',
    tenantId: 'demo-tenant',
    patientId: 'p-6',
    doctorId: 'd-2',
    serviceId: 's-5',
    startTime: '2026-09-10T22:00:00.000Z',
    endTime: '2026-09-10T23:00:00.000Z',
    status: 'CONFIRMED',
    paymentStatus: 'DEPOSIT_PAID',
    depositAmountMxn: 300,
    channelOrigin: 'WHATSAPP',
    symptoms: 'Molestia en muela del juicio',
    notes: 'Anticipo pagado',
    createdAt: '2026-09-09T09:30:00.000Z',
    patient: { id: 'p-6', fullName: 'Roberto Domínguez', phoneE164: '+52 (55) 9988-7711' },
    doctor: { id: 'd-2', name: 'Dr. Alejandro Morales', specialty: 'Cirugía' },
    service: { id: 's-5', name: 'Extracción Muela del Juicio', priceMxn: 1950, durationMinutes: 60 },
  },
];

export const DEMO_DOCTORS: TenantDoctor[] = [
  { id: 'd-1', name: 'Dra. Sofía Silva', specialty: 'Odontología General y Estética' },
  { id: 'd-2', name: 'Dr. Alejandro Morales', specialty: 'Endodoncia y Cirugía' },
];

export const DEMO_SERVICES: TenantService[] = [
  { id: 's-1', name: 'Limpieza Dental con Ultrasonido', priceMxn: 850, durationMinutes: 45, requiredDepositMxn: 200 },
  { id: 's-2', name: 'Blanqueamiento Dental LED', priceMxn: 2600, durationMinutes: 60, requiredDepositMxn: 500 },
  { id: 's-3', name: 'Tratamiento de Conductos', priceMxn: 3200, durationMinutes: 90, requiredDepositMxn: 300 },
];
